[package]
name = "sled-diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
fs-err = "3.0.0"
futures = "0.3.31"
libc = "0.2.166"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["io-util", "macros", "net", "process", "test-util", "time"] }
